# Generated by Django 5.2 on 2025-05-05 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the learning path appears')),
                ('icon_name', models.CharField(default='mortarboard', help_text='Bootstrap icon name', max_length=50)),
                ('auto_unlock', models.BooleanField(default=False, help_text='If True, modules will unlock automatically regardless of prerequisites')),
            ],
            options={
                'verbose_name': 'Learning Path',
                'verbose_name_plural': 'Learning Paths',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('estimated_duration', models.IntegerField(help_text='Duration in minutes')),
                ('difficulty', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='basic', max_length=20)),
                ('icon_name', models.CharField(default='book', help_text="Bootstrap icon name (e.g., 'shield-lock')", max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Order in which the module appears in its learning path')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_badge', models.CharField(blank=True, help_text='Bootstrap icon name for completion badge', max_length=50)),
                ('learning_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='modules.learningpath')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_modules', to='modules.trainingmodule')),
            ],
            options={
                'verbose_name': 'Training Module',
                'verbose_name_plural': 'Training Modules',
                'ordering': ['learning_path', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingModuleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('estimated_time', models.IntegerField(help_text='Estimated time to complete this section in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='modules.trainingmodule')),
            ],
            options={
                'verbose_name': 'Training Module Content',
                'verbose_name_plural': 'Training Module Contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Module Progress',
                'verbose_name_plural': 'User Module Progress Records',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
