# Generated by Django 5.2 on 2025-05-05 08:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={},
        ),
        migrations.RenameField(
            model_name='trainingmodule',
            old_name='estimated_duration',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trainingmodule',
            name='order',
        ),
        migrations.RemoveField(
            model_name='usermoduleprogress',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='usermoduleprogress',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class or image URL', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermoduleprogress',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usermoduleprogress',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='modules.trainingmodule'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='modules.trainingmodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
