# Generated by Django 5.2 on 2025-05-01 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_usermoduleprogress_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Order in which the learning path appears')),
                ('icon_name', models.CharField(default='mortarboard', help_text='Bootstrap icon name', max_length=50)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='dependent_modules', to='modules.trainingmodule'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='modules.learningpath'),
        ),
    ]
