# Generated by Django 5.2 on 2025-05-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_learningpath_trainingmodule_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Learning Path', 'verbose_name_plural': 'Learning Paths'},
        ),
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'ordering': ['learning_path', 'order', 'title'], 'verbose_name': 'Training Module', 'verbose_name_plural': 'Training Modules'},
        ),
        migrations.AlterModelOptions(
            name='usermoduleprogress',
            options={'ordering': ['-last_accessed'], 'verbose_name': 'User Module Progress', 'verbose_name_plural': 'User Module Progress Records'},
        ),
        migrations.AddField(
            model_name='learningpath',
            name='auto_unlock',
            field=models.BooleanField(default=False, help_text='If True, modules will unlock automatically regardless of prerequisites'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='completion_badge',
            field=models.CharField(blank=True, help_text='Bootstrap icon name for completion badge', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='content',
            field=models.TextField(blank=True, help_text='Module content in HTML format', null=True),
        ),
    ]
