# Generated by Django 5.2 on 2025-05-06 14:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_assessmentquestion_modulecontent_userassessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='Learning material (rich text, HTML allowed)'),
        ),
    ]
