# Generated by Django 5.2 on 2025-05-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_learningpath_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='order',
            field=models.IntegerField(default=0, help_text='Order in which the module appears in its learning path'),
        ),
    ]
