# Generated by Django 5.2 on 2025-05-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_modulecontent_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this module is active.'),
        ),
    ]
