# Generated by Django 5.2 on 2025-05-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_trainingmodule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of this module in the learning path'),
        ),
    ]
