# Generated by Django 5.2 on 2025-05-07 10:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_learningpath_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='overview',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Overview or structure of the learning path (supports rich text)', verbose_name='Overview'),
        ),
    ]
