# Generated by Django 5.2 on 2025-05-08 04:58

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_alter_learningpath_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulecontent',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Learning material (rich text, HTML allowed)', verbose_name='Content'),
        ),
    ]
