# Generated by Django 5.2 on 2025-05-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0012_mastercertificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastercertificate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Certificate',
        ),
        migrations.DeleteModel(
            name='MasterCertificate',
        ),
    ]
